export const AVATAR_OPTIONS = [
    { id: 'a1', url: '/avatars/avatar_1.png' },
    { id: 'a2', url: '/avatars/avatar_2.png' },
    { id: 'a3', url: '/avatars/avatar_3.png' },
    { id: 'a4', url: '/avatars/avatar_4.png' },
    { id: 'a5', url: '/avatars/avatar_5.png' },
    { id: 'a6', url: '/avatars/avatar_6.png' },
    { id: 'a7', url: '/avatars/avatar_7.png' },
    { id: 'a8', url: '/avatars/avatar_8.png' },
    { id: 'a9', url: '/avatars/avatar_9.png' },
    { id: 'a10', url: '/avatars/avatar_10.png' },
    { id: 'a11', url: '/avatars/avatar_11.png' },
    { id: 'a12', url: '/avatars/avatar_12.png' },
    { id: 'a13', url: '/avatars/avatar_13.png' },
    { id: 'a14', url: '/avatars/avatar_14.png' },
    { id: 'a15', url: '/avatars/avatar_15.png' },
    { id: 'a16', url: '/avatars/avatar_16.png' },
    { id: 'a17', url: '/avatars/avatar_17.png' },
    { id: 'a18', url: '/avatars/avatar_18.png' },
    { id: 'a19', url: '/avatars/avatar_19.png' },
    { id: 'a20', url: '/avatars/avatar_20.png' },
];
